### ISSUE TITLE
terreria crashes after adding more grass

### ISSUE THREAD

**Issue by mjschmidt** [halkeye-helm-charts/terraria#1]
Environment:
kubernetes version 1.15.5 via minikube
helm chart version 1.1.0
helm v3.0.0

Sorry I don't have better logs but this is what I could get back from the container:
```
24.5% - Adding more grass - 99.6%
24.5% - Adding more grass - 99.7%
24.5% - Adding more grass - 99.8%
24.5% - Adding more grass - 99.9%
24.5% - Adding more grass - 100.0%
24.8% - Adding more grass - 100.0%
24.5% - Adding more grass - 0.0%
24.5% - Desertification - 0.0%
```

**Comment by halkeye** [comment]
check kubectl describe. I'm guessing its liveness probe?

Both this and turtle were some of my earliest helm charts, so probably have the most issues

**Comment by halkeye** [comment]
okay, new version of the chart has probes disabled for now
